### ISSUE TITLE
Define layer in the documentation

### ISSUE THREAD

**Issue by fulv** [plone/plone.app.blocks#22]
In `rendering.rst`, at the beginning of the example the symbol `layer` is referenced without being previously defined:

```
    app = layer['app']
```

If this example is to be followed along (such as in a `bin/instance debug`), perhaps `layer` should be defined.

**Comment by fulv** [comment]
Also in `context.rst`.

**Comment by jensens** [comment]
I suppose ``layer`` refers here to the *plone.testing* test layer.

**Comment by jensens** [comment]
Just looked over this one: layers are documented well in plone.testing, I do not think we need to duble this here.
