### ISSUE TITLE
Latest Releases invisible on pypi

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.blocks#24]
If you go to https://pypi.python.org/pypi/plone.app.blocks/ version 2.2.0 is shown but https://pypi.python.org/pypi/plone.app.blocks/3.0.1 is released.

ping @datakurre @vangheem @esteele

**Comment by datakurre** [comment]
@jensens Would you know, how that could happen? Probably I did the release, but with zest.releaser and I don't remember that anything special happened.

**Comment by jensens** [comment]
@datakurre this may happen if a 2.x series release was made after the latest 3.x series release. but I dont see the history of plone.app.blocks because i dont have access here.

**Comment by jensens** [comment]
@datakurre well, wrong I see 3.0.1 was uploaded 2015-09-23 and 2.2.0 at 2015-10-02 - so thats it.

we may want a warning in zest.releaser if a non-head-of-versions release is made /cc @mauritsvanrees

**Comment by datakurre** [comment]
@jensens Thanks. That was it. I did release 2.2.0 to let c.cover use p.a.blocks with Dexteriyt 1.x (Plone 4.1 and 4.2).

https://pypi.python.org/pypi/plone.app.blocks

**Comment by mauritsvanrees** [comment]
If you login to PyPI you can unhide other releases.  There are different options on showing always the last released package or showing a list of packages. A while ago I have edited some packages to show a list.
- Good: releases stay visible unless you login and explicitly hide them.
- Bad: if you don't login, this list of versions may become long.
I see nothing that zest.releaser can contribute here.

**Comment by jensens** [comment]
@mauritsvanrees My idea was more about a warning: "You are going to upload version 2.0.2. This will hide latest release 3.0.1".

**Comment by gforcada** [comment]
@mauritsvanrees some days ago the same happened to me (just like @jensens reports above). If not on standard zest.releaser we should add that on plone.releaser as to make sure that current versions used by latest Plone 4.x and 5.x are clearly visible on pypi.

Extra cherries on top would  be to make sure the classifiers are updated as well... :-)
