### ISSUE TITLE
An exception on a tile results on a completely broken page

### ISSUE THREAD

**Issue by idgserpro** [plone/plone.app.blocks#27]
In this line you raise an exception https://github.com/plone/plone.app.blocks/blob/1c2e7256c04c86aa55beebd7707f4dee92597ca2/plone/app/blocks/utils.py#L103 and because of that if one tile has an error, all of the tiles become broken.

This happens because if the first tile gets an error, all subsequent rendered tiles gets the error. Something like this:

![broken](https://cloud.githubusercontent.com/assets/8203476/13113421/2387266a-d576-11e5-8947-75cb28820783.png)

Wouldn't it be the case to return an string error, like we had in the past with portlets?

> There was an error while rendering the portlet

> There was an error while rendering this tile

@hvelarde this relates to collective.cover as well.

**Comment by datakurre** [comment]
@idgserpro @hvelarde It's old code, and probably nobody remembers why.

The proper solution is to catch that error in plone.app.blocks.utils.renderTiles, log error and render that placeholder.

**Comment by vangheem** [comment]
this reminds me... I have a fork on blocks that has been used for a long time that does not use subrequest and renders faster.

**Comment by vangheem** [comment]
and does the proper error logging with the placeholder on the tile. I'll make a PR.

**Comment by datakurre** [comment]
I remember that. It felt a bit scary, but if it works... Could it be optional, e.g. by falling back to subrequest with an environment variable (or via ZCA configuration)?

**Comment by vangheem** [comment]
I'm reviewing my fork and I'm actually quite opinionated(have to override plone.tile data managers) so I'm not sure I'll make a PR after all for it. The fork is in the context of a bunch of other changes to how site layouts are used and how tile rendering is done with theming. Time for a sprint to talk about these ideas...

**Comment by datakurre** [comment]
@vangheem Ok. Let's just do a simple fallback rendering error message at first (when next time working with p.a.blocks-code). Barcelona sprint should open new ideas also for Mosaic.

My personal opionion is still that instead of trying to desperately make "rendering of everything at once" faster, we should simply figure out a way to render less in a single request (with tile and layout composition caching and some async approaches).

**Comment by idgserpro** [comment]
> Let's just do a simple fallback rendering error message at first

That's the idea: If you just avoid using `raise` in [that line](https://github.com/plone/plone.app.blocks/blob/1c2e7256c04c86aa55beebd7707f4dee92597ca2/plone/app/blocks/utils.py#L103), and do a

```python
    return _('There was an error while rendering this tile')
```

it works and the error is already logged. We can't do a PR now because of Contributors Agreement.

**Comment by hvelarde** [comment]
we were just bitten by that issue and it was ugly.

**Comment by gforcada** [comment]
@vangheem @datakurre no fixed promises but I'm tentatively planning a mosaic sprint by September this year if possible, after the one that I'm organizing in Berlin already I will start making more specific plans, but would you be interested anyway?

*Sorry for the tangential chat*

**Comment by hvelarde** [comment]
@idgserpro can you guys help on fixing this?

**Comment by idgserpro** [comment]
We told what can be done in https://github.com/plone/plone.app.blocks/issues/27#issuecomment-193384226. It works, and only the tile with an error shows "'There was an error while rendering this tile'" and the cover doesn't break anymore. You can try to add this line of code in the cover you're having issues to see that it solves the problem of breaking it all over.

I think we can have two approaches here: first, do this simple fix, just returning this string; second, improve it like @gforcada and @datakurre are suggesting. One step at a time. :)

**Comment by hvelarde** [comment]
@idgserpro I'm assuming you guys have issues for making a PR on these repost because of the agreement; we will take care of this then.

**Comment by idgserpro** [comment]
@hvelarde @rodfersou Exactly, thanks guys!

For simulating a raise in the tests we did something similar in https://github.com/collective/collective.cover/commit/ef685f8ed686c6e4469d440f5dae1c395c3ee73a, maybe you can have a better idea.

**Comment by hvelarde** [comment]
@idgserpro it's easier: just create a tile that raises an exception.
