### ISSUE TITLE
All IFilters registered twice?

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.blocks#41]
Why are all IFilters registered twice?

```
    <adapter
        for="* .interfaces.IBlocksTransformEnabled"
        name="plone.app.blocks.parsexml"
        factory=".transform.ParseXML"
        />

    <adapter
        for=".interfaces.IBlocksTransformEnabled .interfaces.IBlocksLayer"
        name="plone.app.blocks.parsexml"
        factory=".transform.ParseXML"
    />
```

https://github.com/plone/plone.app.blocks/blob/master/plone/app/blocks/configure.zcml#L132

**Comment by datakurre** [comment]
@jensens https://github.com/plone/plone.app.blocks/issues/11

So, there was need to be able to opt-in to blocks transforms in two ways: either applying marker interface on view or applying marker interface on request.
