### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by krissik** [plone/plone.app.blocks#56]
Finally I have time to test the [permission feature of plone.app.mosaic](https://github.com/plone/plone.app.mosaic/commit/cb8ddad16f798d6cfe8d7bc9db3700dc9200e228). But it is not working with current (4.0.6) version of plone.app.blocks, because of missing `permission` key [which](https://github.com/plone/plone.app.blocks/commit/c5e4894ea45da2396b6c7c7451a3c3e0024b0dd4) was added after last release. 

Is a new release planned?

**Comment by datakurre** [comment]
4.1.0 released

**Comment by datakurre** [comment]
I'm sorry for forgetting versioning policy. That one should have been 4.1 instead.
