### ISSUE TITLE
add contract interface on LayoutAwareTileDataStorage

### ISSUE THREAD

**Issue by iham** [plone/plone.app.blocks#75]
when getting the storage of a tile sometimes you need to sync, sometimes you don't

this is mainly about transient & persistent tiles and i stumbled upon that during learning how to change data on a tile inside a mosaic-layouted contenttype object.

when setting the data to the storage according to the docs
```python
ITileDataManager(tile_view).set(data)
```
this data is not stored when the storage isn't persistent.

by adding this afterwards all is fine
```python
ITileDataManager(tile_view).storage.sync()
```

but not every storage has a sync method!
to be more precise: only the LayoutAwareTileDataStorage has it

so i thought in the shiny world of interfaces i'd ask for its contract, to make sure i only call it, when it's there.
but there is no contract.

i am missing something like
```python
class ILayoutAwareTileDataStorage(ITileDataStorage):
    def sync():
        raise NotImplementedError  # or something like that

@implementer(ILayoutAwareTileDataStorage)
@adapter(...)
class ILayoutAwareTileDataStorage(object):
    ... and so on
```

because then this is possible
```python
storage = ITileDataManager(tile_view).storage
if ILayoutAwareTileDataStorage.providedBy(storage):
    storage.sync()
```

as this is not enough
```python
storage = ITileDataManager(tile_view).storage
if ITileDataStorage.providedBy(storage):
    storage.sync()
```

anything wrong with adding this contract interface?

**Comment by datakurre** [comment]
Requirement for explicit sync is a bug, not a feature.

Did you discover, why it requires explicit sync? It does have implicit sync in its __setitem__.

**Comment by iham** [comment]
@datakurre sadly no.

@jensens helped me a lot on that and might be able to explain, why and how he figured that out.

**Comment by jensens** [comment]
@datakurre It was @iham triying to figure out how to programmatically build a layout in a setup step. So while he figured out how to get the tiles and views, the data never persisted. I debugged into it and found, that sync never got called and so the data never was written into the DB.

Here is the working snippet with sync at the end. w/o sync nothing ist stored.
```
    [...]
    # now we have sorted out which tiles there are
    for t_view in tile_views:
        # lets grab the datamanager adapter
        t_dm_adapter = ITileDataManager(t_view)

        # we can grab informations about it
        # i do a deepcopy to not interfere with the tiles data itself
        data = deepcopy(t_view.data)

        # we can also look this up from the data-manager
        # t_dm_adapter.get()

        # those are common settings on an existingcontent tile
        data['show_title'] = True
        data['show_text'] = True
        data['show_description'] = False
        data['show_image'] = False
        data['show_comments'] = False
        data['content_uid'] = ref_page.UID()

        # now lets 'store' this changes.
        t_dm_adapter.set(data)
        t_dm_adapter.storage.sync()
```

**Comment by datakurre** [comment]
@jensens Thanks. That’s definitely bug, if that requires a sync. Sync was supposed to be called implicitly. It is only implementation detail of storing all tile data in content attribute.

**Comment by datakurre** [comment]
I’ll debug that once I’m on Plone for the next time.

**Comment by datakurre** [comment]
@iham @jensens I stepped this issue now with debugger and for me it appears that `ITileDataManager(tile).set(new_data)` works as expected and data is indeed persistent in the objects' `content` attribute. But because it has cached the value in request using ``@view.memoize``-decorator,  `ITileDataManager(tile).get()` still returns the old value during the same request.

This is also tested in plone.app.blocks tests, but the plone.memoize cache is purged to confirm the persistence of changes in tests.

It's unfortunate that plone.memoize does not have invalidation API, but since this is considered a but, I can fix this by invalidating the cache by copying cache key generation logic from plone.memoize.
