### ISSUE TITLE
[critical] Large html are cut by ParseXML transformer

### ISSUE THREAD

**Issue by tdesvenain** [plone/plone.app.blocks#9]
Large page are cut during transform process, even if they are not concerned by blocks
by example : manage_access pages

**Comment by jensens** [comment]
Is this still an issue?

**Comment by datakurre** [comment]
This is probably still issue for p.a.blocks 1.x with the mentioned lxml versions, but should not be with the later p.a.blocks major versions, because blocks transformation is disabled by default and should not affect ZMI pages.

**Comment by danmur** [comment]
Any way anyone has discovered to fix this on pages that are 200k+ but also need tiles processing? We've got a recent p.a.blocks, 3.1.0.

**Comment by jensens** [comment]
using a recent p.a.blocks with a recent lxml should fix this right?

**Comment by jensens** [comment]
outdated, newer version are fine.
